<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/DHCP.ico</ApplicationIcon>
    <RootNamespace>DhcpFieldServer</RootNamespace>
    <AssemblyName>MYLan</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64</RuntimeIdentifiers>

    <Version>2.1.0</Version>
    <Authors>Rob Handyside - Event Tech Research Ltd</Authors>
    <Product>MYLan DHCP Field Server</Product>
    <Description>A lightweight portable DHCP server for production networks</Description>
    <Copyright>Copyright © 2025-2026 Event Tech Research Ltd</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.1" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

</Project>
