<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>DHCP.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <Authors>Rob Handyside - Event Tech Research Ltd</Authors>
    <Product>MYLan DHCP Field Server</Product>
    <Description>A lightweight portable DHCP server for production networks</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\favicon.ico" />
    <Content Include="DHCP.ico" />
  </ItemGroup>

</Project>
